### ISSUE TITLE
XNAT OHIF Viewer Plugin on XNAT 1.7.4.1

### ISSUE THREAD

**Issue by fldhmily633190808** [JamesAPetts/ohif-viewer-XNAT-plugin#7] opened 2018-09-24 03:55 UTC
Hi,

 I installed the ohif-viewer-1.1.1-SNAPSHOT.jar from https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/master/dist/ohif-viewer-1.1.1-SNAPSHOT.jar

And I copied the jar file in to the $xnat_home/plugins folder as below.

[root@xnathg00014 plugins]# ls -ltr

total 30592

-rwxr-xr-x. 1 tomcat tomcat 15560068 Sep 18  2017 containers-1.2.1-fat.jar.bak

-rwxr-xr-x. 1 tomcat tomcat    37874 Sep 18  2017 xnat-selectable-table-1.0.0.jar

-rwxr-xr-x. 1 tomcat tomcat 15597574 Oct 11  2017 containers-1.3-fat.jar

-rwxr-xr-x. 1 tomcat tomcat    69744 Oct 18  2017 non-dicom-uploader.jar

-rwxr-xr-x. 1 tomcat tomcat    48342 Sep 21 12:12 ohif-viewer-1.1.1-SNAPSHOT.jar

After this I restarted the tomcat, however, I cannot see the viewer plugin in the Site Administrator -> Installed Plugins, and I couldn't see that shown ?

And i cannot see the new viewer shown in the session. Is there anything i did not do correctly ?
![screen shot 2018-09-21 at 2 44 07 pm](https://user-images.githubusercontent.com/29057117/45937222-8265a580-c001-11e8-863e-7637549f02ed.png)

**Comment by fldhmily633190808** [comment] 2018-09-24 03:56
I also posted on XNAT google Groups, thanks for the assistance greatly!

https://groups.google.com/forum/#!topic/xnat_discussion/_6gOaICx2wY

**Comment by JamesAPetts** [comment] 2018-10-01 09:12
@fldhmily633190808, sorry for the delay in responding to this.

The plugin should be plug and play with a default xnat-vagrant setup. I'm also running a copy of XNAT 1.7.4.1 on my test instance. I just tried the distribution you are trying to use and had no problems.

Its interesting that other plugins work for you.

I've gone largely off the XNAT plugin tutorials available online from a workshop a few years back. Perhaps there is some more boilerplate to get plugins working on all systems that I'm unaware of.

How are you setting up/configuring your xnat?
- Is your XNAT instance running on linux, OSX or  windows? If your XNAT is running on Windows I know there can be strange issues with the plugin framework, as Windows was officially no longer supported as of 3 years ago.
- Are you running a vagrant VM, docker-ized XNAT, or some custom install/Tomcat configuration?

With a little more info hopefully I can point you in the right direction to fix this issue.

Out of interest, give Beta 1.5.2 of the new ROI version a go. It's two plugins available here:
https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/tree/xnatRoi-beta-1.5/dist

Even if the new functionality is overkill for your needs, I'd be interested to see if these plugins have the same registration issues you are having with 1.1.1.

Kind regards,
JamesAPetts

**Comment by fldhmily633190808** [comment] 2018-10-02 08:07
@JamesAPetts 

Thanks James for replying back. The XNAT application is installed on RHEL6.9 machine in our data centers], with PostgreSQL 9.5 installed on the same machine, and local filesystem.  We set tomcat:tomcat as the xnat directory owners.

We have also implemented the XNAT instance on RHEL7.5 in AWS, using AWS Relational Database Services (RDS) and AWS EFS (Elastic File System), but I did not try to install the plugins over there.

But I will try the new ROI versions you provided and see how it goes

**Comment by fldhmily633190808** [comment] 2018-10-02 08:19
I tried the new plugin, seemed not working either.

[root@xnathg00014 plugins]# ls -ltr
total 30592
-rwxr-xr-x. 1 tomcat tomcat 15560068 Sep 18  2017 containers-1.2.1-fat.jar.bak
-rwxr-xr-x. 1 tomcat tomcat    37874 Sep 18  2017 xnat-selectable-table-1.0.0.jar
-rwxr-xr-x. 1 tomcat tomcat 15597574 Oct 11  2017 containers-1.3-fat.jar
-rwxr-xr-x. 1 tomcat tomcat    69744 Oct 18  2017 non-dicom-uploader.jar
-rwxr-xr-x. 1 tomcat tomcat    48179 Oct  2 18:10 ohif-viewer-BETA-1.5.4-SNAPSHOT.jar
[root@xnathg00014 plugins]# service tomcat stop;service tomcat start
Stopping tomcat:                                           [  OK  ]
Starting tomcat:                                           [  OK  ]

Same problem
## I tried to rename all the other plugins other than the  ohif-viewer-BETA-1.5.4-SNAPSHOT.jar, still dont work.

root@xnathg00014 plugins]# mv ./xnat-selectable-table-1.0.0.jar ./xnat-selectable-table-1.0.0.jar.bak
[root@xnathg00014 plugins]# mv ./containers-1.3-fat.jar ./containers-1.3-fat.jar.bak
[root@xnathg00014 plugins]# mv ./non-dicom-uploader.jar ./non-dicom-uploader.jar.bak
[root@xnathg00014 plugins]# ls -ltr
total 15396
-rwxr-xr-x. 1 tomcat tomcat    37874 Sep 18  2017 xnat-selectable-table-1.0.0.jar.bak
-rwxr-xr-x. 1 tomcat tomcat 15597574 Oct 11  2017 containers-1.3-fat.jar.bak
-rwxr-xr-x. 1 tomcat tomcat    69744 Oct 18  2017 non-dicom-uploader.jar.bak
-rwxr-xr-x. 1 tomcat tomcat    48179 Oct  2 18:10 ohif-viewer-BETA-1.5.4-SNAPSHOT.jar
[root@xnathg00014 plugins]# service tomcat stop; service tomcat start
Stopping tomcat:                                           [  OK  ]
Starting tomcat:                                           [  OK  ]

![image](https://user-images.githubusercontent.com/29057117/46336970-a8c5b980-c66f-11e8-94c5-eeaf81fde68f.png)

**Comment by fldhmily633190808** [comment] 2018-10-02 08:33
## same problem for XNAT at RHEL7.5 on AWS

[ec2-user@ip-***~]$ sudo -i
[root@ip-*** ~]# cd /efs/data/xnat/home/plugins
[root@ip-***plugins]# ls -ltr
total 8
-rw-r--r--. 1 tomcat tomcat 916 May 15 14:36 ldap.jar
-rw-r--r--. 1 tomcat tomcat 784 May 15 14:40 localdb.jar
[root@ip-*** plugins]# wget https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/xnatRoi-beta-1.5/dist/ohif-viewer-BETA-1.5.4-SNAPSHOT.jar
--2018-10-02 18:26:04--  https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/xnatRoi-beta-1.5/dist/ohif-viewer-BETA-1.5.4-SNAPSHOT.jar
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘ohif-viewer-BETA-1.5.4-SNAPSHOT.jar’

    [  <=>                                                                    ] 48,179       148KB/s   in 0.3s   

2018-10-02 18:26:05 (148 KB/s) - ‘ohif-viewer-BETA-1.5.4-SNAPSHOT.jar’ saved [48179]

[root@ip-*** plugins]# ls -ltr
total 56
-rw-r--r--. 1 tomcat tomcat   916 May 15 14:36 ldap.jar
-rw-r--r--. 1 tomcat tomcat   784 May 15 14:40 localdb.jar
-rw-r--r--. 1 root   root   48179 Oct  2 18:26 _**ohif-viewer-BETA-1.5.4-SNAPSHOT.jar**_

Try 'chmod --help' for more information.
[root@ip-*** plugins]# chown tomcat:tomcat ohif-viewer-BETA-1.5.4-SNAPSHOT.jar 
[root@ip-1*** plugins]# ls -ltr
total 56
-rw-r--r--. 1 tomcat tomcat   916 May 15 14:36 ldap.jar
-rw-r--r--. 1 tomcat tomcat   784 May 15 14:40 localdb.jar
-rw-r--r--. 1 tomcat tomcat 48179 Oct  2 18:26 ohif-viewer-BETA-1.5.4-SNAPSHOT.jar
[root@ip-*** plugins]# systemctl stop tomcat; systemctl start tomcat

![image](https://user-images.githubusercontent.com/29057117/46337675-74eb9380-c671-11e8-871f-59527176d7f4.png)


Please let me know if you need to view any logs

**Comment by JamesAPetts** [comment] 2018-10-02 09:02
Hey @fldhmily633190808 , thanks for the wealth of info. I'm going to pass this on to the core XNAT team.

EDIT: It seems your command for wget on the dist doesn't download the whole file! We just had this issue whilst setting up an independent dev server!

If you instead use this URL to grab the raw file of 1.1.1., everything should be fine:

https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/raw/master/dist/ohif-viewer-1.1.1-SNAPSHOT.jar

~~The fact other plugins register implies that there may be some configuration missing within my plugin, undocumented in the tutorials, that is causing it to not function properly on some systems. I know one user had a similar problem on Windows that the XNAT team helped with. The XNAT guys have installed the plugin successfully on an AWS hosted XNAT, so I think the problem is definitely solvable. Hopefully I can solve it in a general sense so that no configuration is needed for any system.~~

~~May you send me your e-mail to jamesapetts@gmail.com, so that I can CC you in any correspondence?~~

**Comment by fldhmily633190808** [comment] 2018-10-04 01:31
@JamesAPetts Thanks for this. It worked fine for the OHIF-VIewer-1.1.1-Snapshot.Jar. 
There is another issue i would like to ask

(1) When there is only one scan the we click in the whole session, it will open perfectly. 
(2) As you can see from the screenshot, if there are multiple scans in one session, and the sessions are very large data set. But we just want to open the "970" scan which is around 100MB, it will not be opened at all.

![image](https://user-images.githubusercontent.com/29057117/46448152-c22e4900-c7c8-11e8-8686-601303375b55.png)

**Comment by fldhmily633190808** [comment] 2018-10-04 01:31
And i kept getting the messages:
![image](https://user-images.githubusercontent.com/29057117/46448218-0d485c00-c7c9-11e8-9a5f-031c9b581af2.png)

**Comment by fldhmily633190808** [comment] 2018-10-04 01:49
The one i mentioned above (1) had success is on another server,
on the (2) server, looked like there were issues as shown in the screenshot
![image](https://user-images.githubusercontent.com/29057117/46448688-792bc400-c7cb-11e8-86d3-1e0ebc669568.png)

**Comment by JamesAPetts** [comment] 2018-10-04 09:12
>But we just want to open the "970" scan which is around 100MB, it will not be opened at all.

The table plugin has no integration with the OHIF viewer plugin at all. Because of ambiguous plugin loading in XNAT, it is currently not possible to have plugins that depend on plugins. 'View Session' is the only way to load images, the table plugin is linking to the old XImgViewer. This will change in the future when the table plugin goes core (in the near future with 1.7.5 I believe).

> And i kept getting the messages:

The automation system in 1.7.4 is super flakey and works for some people at not others. I'm waiting for the new automation system in 1.8 which is apparently more stable. If the JSON data isn't being auto-generated, you currently have to wait until it is called. You can manually trigger the JSON generation for a single session, or for the whole DB (as Admin) through the swigger interface at: XNAT_URL/xapi/swagger-ui.html.

> The one i mentioned above (1) had success is on another server,
on the (2) server, looked like there were issues as shown in the screenshot.

Is your `site url` in `Administer/Site Administration/Site Setup` in your XNAT interface the same as the url used to reach the site, including port extension (once past any proxies)?

**Comment by fldhmily633190808** [comment] 2018-10-05 05:27
Hi James,

for the ones we have in our Data centers, both servers are working fine now. I will let you know when we have some more new issues. 


> Is your `site url` in `Administer/Site Administration/Site Setup` in your XNAT interface the same as the url used to reach the site, including port extension (once past any proxies)?

Yes it is.

**Comment by JamesAPetts** [comment] 2018-10-05 09:14
Hey @fldhmily633190808 , glad things are working out for you.

Just to confirm, you no longer get the `Error Loading Image` problem on either server? In general that issue denotes a malformed url, so rebuilding the metadata might have helped.

Thanks,
James

**Comment by fldhmily633190808** [comment] 2018-10-06 09:38
The session is still having the issue for "Error loading Image". But after I upload the data onto a new session, the new session worked. I guess that could be a random issue. But will report if i find some new issues.

**Comment by JamesAPetts** [comment] 2018-10-06 11:38
@fldhmily633190808 , if it worked for a duplicate session, you likely just need to rebuild the metadata. You can do this via REST, do a POST on the metadata. You can see the OHIF viewer api via the swagger interface, which you can access through the adminster interface under miscellaneous. Glad its working well for now.

Feel free to give any feedback, its still a work in progress and we have a lot of plans going forward! :)_

**Comment by JamesAPetts** [comment] 2018-10-08 08:59
@fldhmily633190808 , I'll close this for now, as you appear to be on track, but feel free to reopen the issue if you have continuing issues, or create a different issue if you have a different distinct issue.

Thanks,
James

**Closed as completed by JamesAPetts** 2018-10-08 08:59 UTC
